name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 16 * * *'
  # Manual Option
  # workflow_dispatch:

jobs:
  study:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 50
