name: Get Duolingo XPs for my account (Manual)

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 10
        description: 'Number of lessons to be completed'
        required: true
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.default }}
